### ISSUE TITLE
About your trained model using adversarial training

### ISSUE THREAD

**Issue by shenqixiaojiang** [ftramer/ensemble-adv-training#1]
Could you mind releasing  your trained Inception v3 model using adversarial training on the ImageNet datasets?
Thanks.

**Comment by ftramer** [comment]
Hi,

Alexey released adversarially trained ImageNet models here: https://github.com/tensorflow/models/tree/master/adv_imagenet_models

**Comment by shenqixiaojiang** [comment]
@ftramer Wow， Thank you very much.

**Comment by shenqixiaojiang** [comment]
The new link of adversarially trained ImageNet models is here:
https://github.com/tensorflow/models/tree/master/research/adv_imagenet_models
